[2025-10-31T00:25:28.599+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-31T00:25:28.767+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_workflow.dbt_run scheduled__2025-10-30T00:00:00+00:00 [queued]>
[2025-10-31T00:25:28.829+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_workflow.dbt_run scheduled__2025-10-30T00:00:00+00:00 [queued]>
[2025-10-31T00:25:28.834+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2025-10-31T00:25:28.914+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): dbt_run> on 2025-10-30 00:00:00+00:00
[2025-10-31T00:25:28.935+0000] {standard_task_runner.py:72} INFO - Started process 180 to run task
[2025-10-31T00:25:28.948+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_workflow', 'dbt_run', 'scheduled__2025-10-30T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/dbt_workflow_dag.py', '--cfg-path', '/tmp/tmpytt4utxy']
[2025-10-31T00:25:28.977+0000] {standard_task_runner.py:105} INFO - Job 2: Subtask dbt_run
[2025-10-31T00:25:29.411+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_workflow.dbt_run scheduled__2025-10-30T00:00:00+00:00 [running]> on host 7fe02f4c3e0d
[2025-10-31T00:25:29.687+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_workflow' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-10-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-30T00:00:00+00:00'
[2025-10-31T00:25:29.690+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-31T00:25:29.825+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T00:25:29.832+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd C:/Users/bousl/OneDrive/Documents/datapipeline/snowflake_data && dbt run']
[2025-10-31T00:25:29.856+0000] {subprocess.py:86} INFO - Output:
[2025-10-31T00:25:29.880+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: cd: C:/Users/bousl/OneDrive/Documents/datapipeline/snowflake_data: No such file or directory
[2025-10-31T00:25:29.881+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-31T00:25:29.926+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-31T00:25:29.973+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_workflow, task_id=dbt_run, run_id=scheduled__2025-10-30T00:00:00+00:00, execution_date=20251030T000000, start_date=20251031T002528, end_date=20251031T002529
[2025-10-31T00:25:30.023+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-31T00:25:30.028+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 2 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 180)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-31T00:25:30.070+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2025-10-31T00:25:30.105+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-31T00:25:30.108+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
