[2025-10-31T00:38:35.037+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-31T00:38:35.080+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_workflow.dbt_run manual__2025-10-31T00:37:29.342683+00:00 [queued]>
[2025-10-31T00:38:35.099+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_workflow.dbt_run manual__2025-10-31T00:37:29.342683+00:00 [queued]>
[2025-10-31T00:38:35.101+0000] {taskinstance.py:2856} INFO - Starting attempt 2 of 2
[2025-10-31T00:38:35.136+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): dbt_run> on 2025-10-31 00:37:29.342683+00:00
[2025-10-31T00:38:35.151+0000] {standard_task_runner.py:72} INFO - Started process 194 to run task
[2025-10-31T00:38:35.158+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_workflow', 'dbt_run', 'manual__2025-10-31T00:37:29.342683+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dbt_workflow_dag.py', '--cfg-path', '/tmp/tmp8jdnlkqi']
[2025-10-31T00:38:35.165+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask dbt_run
[2025-10-31T00:38:35.309+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_workflow.dbt_run manual__2025-10-31T00:37:29.342683+00:00 [running]> on host 9bb3f8682efa
[2025-10-31T00:38:35.461+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_workflow' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T00:37:29.342683+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-31T00:37:29.342683+00:00'
[2025-10-31T00:38:35.463+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-31T00:38:35.513+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T00:38:35.516+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd C:/Users/bousl/OneDrive/Documents/datapipeline/snowflake_data && dbt run']
[2025-10-31T00:38:35.544+0000] {subprocess.py:86} INFO - Output:
[2025-10-31T00:38:35.562+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: cd: C:/Users/bousl/OneDrive/Documents/datapipeline/snowflake_data: No such file or directory
[2025-10-31T00:38:35.563+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-31T00:38:35.583+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-31T00:38:35.596+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=dbt_workflow, task_id=dbt_run, run_id=manual__2025-10-31T00:37:29.342683+00:00, execution_date=20251031T003729, start_date=20251031T003835, end_date=20251031T003835
[2025-10-31T00:38:35.618+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-31T00:38:35.621+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 3 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 194)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-31T00:38:35.677+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2025-10-31T00:38:35.709+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-31T00:38:35.715+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
